### ISSUE TITLE
Provide instruction for Dummies

### ISSUE THREAD

**Issue by razbakov** [Zookal/DocHarris#1]
Hi there,

I have never used Docker before and I am really frustrating.
I am just looking for simple command to run docker and see how it works.

Please provide detail instructions what to do. 

And clarify parameters. For example:

> boot2docker --vbox-share=/Users/xxx/Sites/web-site=site --vbox-share=/Users/xxx/Sites/web-data=data -v init

What does it mean here `=site` and `=data`?

**Comment by SchumacherFM** [comment]
There are many documentations and tutorials out there much better than I can provide.

You can e.g. start here http://boot2docker.io/

**Comment by razbakov** [comment]
Can you at least answer my question, please?

> boot2docker --vbox-share=/Users/xxx/Sites/web-site=site --vbox-share=/Users/xxx/Sites/web-data=data -v init

What does it mean here `site` and `data`?
